from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
import os
import textwrap

def split_text_into_chunks(text, max_lines=7, wrap_width=80):
    lines = []
    for paragraph in text.split("\n"):
        wrapped = textwrap.wrap(paragraph, width=wrap_width)
        lines.extend(wrapped if wrapped else [""])
    for i in range(0, len(lines), max_lines):
        yield lines[i:i + max_lines]

def add_title_slide(prs, title, subtitle="Generated by GenAI Market Summarizer"):
    slide = prs.slides.add_slide(prs.slide_layouts[0])
    slide.shapes.title.text = title
    slide.placeholders[1].text = subtitle

def add_bullet_slide(prs, title, bullet_lines):
    slide = prs.slides.add_slide(prs.slide_layouts[1])
    slide.shapes.title.text = title
    content = slide.placeholders[1]
    content.text = ""
    for line in bullet_lines:
        p = content.text_frame.add_paragraph()
        p.text = line
        p.level = 0
        p.font.size = Pt(18)

def add_image_slide(prs, title, image_path):
    if not os.path.exists(image_path):
        print(f"⚠️ Image not found: {image_path}")
        return
    slide = prs.slides.add_slide(prs.slide_layouts[5])  # Blank layout

    # Add title
    title_shape = slide.shapes.add_textbox(Inches(0.5), Inches(0.2), Inches(9), Inches(0.5))
    frame = title_shape.text_frame
    frame.text = title
    frame.paragraphs[0].font.size = Pt(24)
    frame.paragraphs[0].font.bold = True

    # Add image
    slide.shapes.add_picture(image_path, Inches(1), Inches(1.2), width=Inches(8))

from pptx import Presentation
from pptx.util import Inches

def generate_presentation(title, summary_text, charts, market_overview, key_insights):
    prs = Presentation()

    # Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = title
    slide.placeholders[1].text = "Generated by GenAI Market Summarizer"

    # Market Overview Slide
    bullet_slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(bullet_slide_layout)
    slide.shapes.title.text = "Market Overview"
    slide.placeholders[1].text = market_overview

    # Key Insights Slide
    slide = prs.slides.add_slide(bullet_slide_layout)
    slide.shapes.title.text = "Key Insights"
    body_shape = slide.placeholders[1]
    tf = body_shape.text_frame
    for insight in key_insights:
        p = tf.add_paragraph()
        p.text = insight

    # AI Summary Slide
    slide = prs.slides.add_slide(bullet_slide_layout)
    slide.shapes.title.text = "AI Summary"
    slide.placeholders[1].text = summary_text

    # Charts Slides
    for chart_path in charts:
        slide = prs.slides.add_slide(prs.slide_layouts[5])  # Blank layout
        slide.shapes.title.text = "Chart"
        left = Inches(1)
        top = Inches(1.5)
        pic = slide.shapes.add_picture(chart_path, left, top, width=Inches(6), height=Inches(4.5))

    # Custom Slides
    for i in range(1, 4):
        slide = prs.slides.add_slide(bullet_slide_layout)
        slide.shapes.title.text = f"Custom Slide {i}"
        slide.placeholders[1].text = "Your content here."

    # Save Presentation
    pptx_path = "comparison_report.pptx"
    prs.save(pptx_path)
    return pptx_path
